name: CI Pipeline

on:
  push:
    branches:
      - version-1
  pull_request:
    branches:
      - version-1

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ‘8.3’
          extensions: mbstring, xml, ctype, json, curl, mysql
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ‘latest’

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Unit Tests
        run: php artisan test --env=testing --parallel

      - name: Run JavaScript Linting and Tests
        run: |
          npm run lint
          npm run test